lint.select = ["ALL"]
lint.ignore = [
    "ANN101", # Missing type annotation for {name} in method
    "D100",   # Missing docstring in public module
    "D103",   # Missing docstring in public function
    "D203",   # 1 blank line required before class docstring
    "D212",   # Multi-line docstring summary should start at the first line
    "E501",   # Line too long ({width} > {limit})
]
